### ISSUE TITLE
runner_on_ok() takes 3 arguments now.

### ISSUE THREAD

**Issue by bbaassssiiee** [ginsys/ansible-plugins#10]
[WARNING]: Failure when attempting to use callback plugin

plugins/callback_plugins/human_log.CallbackModule

runner_on_ok() takes exactly 3 arguments (2 given)

**Comment by srgvg** [comment]
Your description is not very clear, and lacks lots of information on how to reproduce this.

That being said, plugins are written vor Ansible 1.X and are not updated yet for 2.X, which uses a different API for certain plugins.

**Comment by bbaassssiiee** [comment]
That explains, I was using the plugin with ansible 2.0.1.0. Thx!
